In [1]:
import pandas as pd
import numpy as np

working_file=pd.read_csv('Desktop/Kaggle/Penaltycheck-master/Football Penalty Data.csv',encoding='latin')
working_file.head()

No.  Match Week       Date              Player        Team       Versus  \
0    1           1  13-Aug-16        Riyad Mahrez   Leicester         Hull   
1    2           1  13-Aug-16       Sergio Agüero    Man City   Sunderland   
2    3           1  14-Aug-16        Theo Walcott     Arsenal    Liverpool   
3    4           1  15-Aug-16         Eden Hazard     Chelsea     West Ham   
4    5           2  19-Aug-16  Zlatan Ibrahimovic  Man United  Southampton   

                       Match Time of Penalty Awarded  Scored Foot  \
0          Hull vs Leicester              47' minute  Scored    L   
1     Man City vs Sunderland               4' minute  Scored    R   
2       Arsenal vs Liverpool              30' minute  Missed    R   
3        Chelsea vs West Ham              47' minute  Scored    R   
4  Man United vs Southampton              52' minute  Scored    R   

  Kick_Direction Keeper_Direction  
0              C                R  
1              L                L  
2              L                L  
3              C                L  
4              L                R

In [2]:
working_file.isnull()

No.  Match Week   Date  Player   Team  Versus  Match  \
0    False       False  False   False  False   False  False   
1    False       False  False   False  False   False  False   
2    False       False  False   False  False   False  False   
3    False       False  False   False  False   False  False   
4    False       False  False   False  False   False  False   
..     ...         ...    ...     ...    ...     ...    ...   
98   False       False  False   False  False   False  False   
99   False       False  False   False  False   False  False   
100  False       False  False   False  False   False  False   
101  False       False  False   False  False   False  False   
102  False       False  False   False  False   False  False   

     Time of Penalty Awarded  Scored   Foot  Kick_Direction  Keeper_Direction  
0                      False   False  False           False             False  
1                      False   False  False           False             False  
2                      False   False  False           False             False  
3                      False   False  False           False             False  
4                      False   False  False           False             False  
..                       ...     ...    ...             ...               ...  
98                     False   False  False           False             False  
99                     False   False  False           False             False  
100                    False   False  False           False             False  
101                    False   False  False           False             False  
102                    False   False  False           False             False  

[103 rows x 12 columns]

In [3]:
working_file.isnull().sum()

No.                        0
Match Week                 0
Date                       0
Player                     0
Team                       0
Versus                     0
Match                      0
Time of Penalty Awarded    0
Scored                     0
Foot                       0
Kick_Direction             0
Keeper_Direction           0
dtype: int64

In [4]:
working_file['Team'].value_counts()

Bournemouth       9
Man City          9
Tottenham         9
Liverpool         8
Stoke             6
Arsenal           6
Southampton       6
Crystal Palace    6
West Ham          5
Sunderland        5
Burnley           5
Leicester         5
Everton           4
Man United        4
Chelsea           4
Watford           3
Hull              3
Swansea           3
Middlesbrough     2
West Brom         1
Name: Team, dtype: int64

In [5]:
working_file.describe

<bound method NDFrame.describe of      No.  Match Week       Date              Player            Team  \
0      1           1  13-Aug-16        Riyad Mahrez       Leicester   
1      2           1  13-Aug-16       Sergio Agüero        Man City   
2      3           1  14-Aug-16        Theo Walcott         Arsenal   
3      4           1  15-Aug-16         Eden Hazard         Chelsea   
4      5           2  19-Aug-16  Zlatan Ibrahimovic      Man United   
..   ...         ...        ...                 ...             ...   
98   101          37  13-May-17       Gabriel Jesus        Man City   
99   102          37  13-May-17          Shane Long     Southampton   
100  104          37  14-May-17    Luka Milivojevic  Crystal Palace   
101  105          37  17-May-17   Manolo Gabbiadini     Southampton   
102  106          38  21-May-17       Romelu Lukaku         Everton   

            Versus                         Match Time of Penalty Awarded  \
0             Hull             Hull v

In [6]:
working_file.shape

(103, 12)

In [7]:
working_file['Player'].value_counts()

James Milner          8
Harry Kane            6
Jermain Defoe         5
Sergio Agüero         5
Riyad Mahrez          4
Leighton Baines       3
Zlatan Ibrahimovic    3
Christian Benteke     3
Callum Wilson         3
Gylfi Sigurdsson      3
Alexis Sánchez        3
Troy Deeney           3
Eden Hazard           3
Bojan Krkic           3
Joshua King           3
Yaya Touré            2
Sam Vokes             2
Dušan Tadi?           2
Robert Snodgrass      2
Charlie Austin        2
Junior Stanislas      2
Mark Noble            2
Andre Gray            2
Santiago Cazorla      2
Álvaro Negredo        2
Manuel Lanzini        2
Luka Milivojevic      2
Yohan Cabaye          1
Jonathan Walters      1
Nacer Chadli          1
Ashley Barnes         1
Vincent Janssen       1
Manolo Gabbiadini     1
Harry Arter           1
Diego Costa           1
Benik Afobe           1
Islam Slimani         1
Romelu Lukaku         1
Gabriel Jesus         1
Wayne Rooney          1
Shane Long            1
Erik Lamela     

In [8]:
x=working_file.values[:,0:10]
y=working_file.values[:,10]
x

array([[1, 1, '13-Aug-16', ..., "47' minute", 'Scored', 'L'],
       [2, 1, '13-Aug-16', ..., "4' minute", 'Scored', 'R'],
       [3, 1, '14-Aug-16', ..., "30' minute", 'Missed', 'R'],
       ...,
       [104, 37, '14-May-17', ..., "85' minute", 'Scored', 'R'],
       [105, 37, '17-May-17', ..., "6' minute", 'Missed', 'L'],
       [106, 38, '21-May-17', ..., "58' minute", 'Scored', 'L']],
      dtype=object)

In [9]:
    x[:,2]=pd.factorize(x[:,2])[0]
    x[:,3]=pd.factorize(x[:,3])[0]
    x[:,4]=pd.factorize(x[:,4])[0]
    x[:,5]=pd.factorize(x[:,5])[0]
    x[:,6]=pd.factorize(x[:,6])[0]
    x[:,7]=pd.factorize(x[:,7])[0]
    x[:,8]=pd.factorize(x[:,8])[0]
    x[:,9]=pd.factorize(x[:,9])[0]
x

array([[1, 1, 0, ..., 0, 0, 0],
       [2, 1, 0, ..., 1, 0, 1],
       [3, 1, 1, ..., 2, 1, 1],
       ...,
       [104, 37, 53, ..., 61, 0, 1],
       [105, 37, 54, ..., 29, 1, 0],
       [106, 38, 55, ..., 40, 0, 0]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=4)

In [11]:
from sklearn.linear_model import LogisticRegression
cf=LogisticRegression()

In [12]:
cf.fit(x_train, y_train)


c:\python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_pred=cf.predict(x_test)

In [14]:
print(y_pred)

['R' 'C' 'L' 'R' 'L' 'R' 'C' 'R' 'R' 'R' 'L' 'R' 'R' 'L' 'C' 'L' 'L' 'L'
 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'C']


In [15]:
cf.predict_proba(x_test)

array([[0.20340964, 0.24146381, 0.55512655],
       [0.55935032, 0.09653345, 0.34411623],
       [0.06779734, 0.50665381, 0.42554886],
       [0.21391232, 0.3482747 , 0.43781298],
       [0.09965693, 0.47069281, 0.42965026],
       [0.2427795 , 0.26732058, 0.48989991],
       [0.35542677, 0.35200566, 0.29256756],
       [0.0776496 , 0.32619701, 0.59615339],
       [0.26695111, 0.31734693, 0.41570196],
       [0.10990196, 0.41624286, 0.47385518],
       [0.06832138, 0.62700729, 0.30467133],
       [0.28345026, 0.27065341, 0.44589634],
       [0.12130338, 0.24952163, 0.62917499],
       [0.10121688, 0.76151522, 0.1372679 ],
       [0.47545388, 0.19321716, 0.33132896],
       [0.1286592 , 0.524349  , 0.3469918 ],
       [0.24838119, 0.4397406 , 0.31187821],
       [0.09860079, 0.69326669, 0.20813252],
       [0.35670053, 0.25679421, 0.38650526],
       [0.09484926, 0.37882863, 0.52632211],
       [0.15544807, 0.22928183, 0.61527011],
       [0.05212542, 0.54745355, 0.40042102],
       [0.

In [16]:
cf.score(x_test,y_test)

0.6923076923076923

In [17]:
from sklearn import metrics
import seaborn as sns

In [18]:
cnf_matrix=metrics.confusion_matrix(y_test,y_pred)
cnf_matrix

array([[1, 0, 2],
       [3, 9, 1],
       [0, 2, 8]], dtype=int64)

In [19]:
metrics.accuracy_score(y_test,y_pred)

0.6923076923076923